### ISSUE TITLE
GSoC 2019 - new person error

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#26]
Adding a new person throws an error
```

Request Method: | POST
-- | --
http://127.0.0.1:8000/en/cms_wizard/create/
2.1.7
TypeError
render() got an unexpected keyword argument 'renderer'
C:\Python36\lib\site-packages\django\forms\boundfield.py in as_widget, line 93
C:\Python36\python.exe
3.6.8
['D:\\development\\python-blog\\python-blogs',  'C:\\Python36\\python36.zip',  'C:\\Python36\\DLLs',  'C:\\Python36\\lib',  'C:\\Python36',  'C:\\Python36\\lib\\site-packages']
Thu, 14 Feb 2019 22:50:30 -0800

[14/Feb/2019 23:49:37] "GET /en/cms_wizard/create/?page=21&language=en&edit&cms_path=/en/test/test123/ HTTP/1.1" 200 13648
Internal Server Error: /en/cms_wizard/create/
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python36\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python36\lib\site-packages\django\core\handlers\base.py", line 154, in _get_response
    response = response.render()
  File "C:\Python36\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Python36\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "C:\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Python36\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python36\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Python36\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python36\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Python36\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python36\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Python36\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python36\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python36\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python36\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "C:\Python36\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python36\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 993, in render
    return render_value_in_context(output, context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 972, in render_value_in_context
    value = str(value)
  File "C:\Python36\lib\site-packages\django\utils\html.py", line 397, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "C:\Python36\lib\site-packages\django\forms\boundfield.py", line 33, in __str__
    return self.as_widget()
  File "C:\Python36\lib\site-packages\django\forms\boundfield.py", line 93, in as_widget
    renderer=self.form.renderer,
TypeError: render() got an unexpected keyword argument 'renderer'
[14/Feb/2019 23:50:31] "POST /en/cms_wizard/create/ HTTP/1.1" 500 291959
```

**Comment by shashank-sharma** [comment]
I'll take up this issue, just to be sure it's all happening after upgrading from 11.18 to 2+

**Comment by botanicvelious** [comment]
not entirely sure I just noticed it after the upgrade but probably? 👍

**Comment by botanicvelious** [comment]
Issue #24 may be related.

**Comment by botanicvelious** [comment]
Part 1 and 2 are fixed by issues #24 fix

Part 3 is still broken, still can't add a person, looks to be an issue in django cms so if that is the case we need to report an issue to them

**Comment by botanicvelious** [comment]
Cleaned up original issue
